---
# Use ddclient to setup a free (or cheap) subdomain with a dynamic dns provider
- hosts: buyvm
  
  vars_prompt:
    - name: ddclient_password
      prompt: Password to your dynamic dns provider account (eg. freedns)
      private: yes

  sudo: yes

  tasks:

    - name: install ddclient
      apt: pkg=ddclient default_release=unstable state=present

    - name: install libdigest-sha-perl for ddclient (needed for freedns)
      apt: pkg=libdigest-sha-perl state=present

    # ddclient on debian is missing a patch for freedns
    # http://sourceforge.net/p/ddclient/discussion/399428/thread/9742ac09/
    - name: install cpanminus for Digest::SHA1 (due to ddclient bug)
      apt: pkg=cpanminus state=present

    - name: install Digest::SHA1 (due to ddclient bug)
      command: cpanm Digest::SHA1

    - name: configure ddclient
      template: >
        src=resources/etc/ddclient.conf
        dest=/etc/ddclient.conf
        owner=root
        group=root
        mode=600

    - name: restart ddclient
      service: name=ddclient state=restarted
