---
# Setup a lightweight single-user mailserver using postfix (MTA) and dovecot
# (IMAP server).
- hosts: buyvm
  sudo: yes
  tasks:

    - name: uninstall exim4
      apt: pkg={{item}} state=absent purge=yes
      with_items:
        - exim4
        - exim4-base
        - exim4-config
        - exim4-daemon-light

    - name: install postfix
      apt: pkg=postfix state=present

    - name: configure postfix
      template: >
        src=resources{{ item }}
        dest={{ item }}
        owner=root
        group=root
        mode=644
      with_items:
        - /etc/aliases
        - /etc/mailname
        - /etc/postfix/main.cf
        - /etc/postfix/master.cf
      notify:
        - run newaliases
        - restart postfix

    - name: install dovecot
      apt: pkg={{item}} state=present
      with_items:
        - dovecot-core
        - dovecot-sqlite

    - name: configure dovecot
      template: >
        src=resources{{ item }}
        dest={{ item }}
        owner=root
        group=root
        mode=644
      with_items:
        - /etc/pam.d/dovecot
      notify:
        - restart dovecot

    # Being able to manage email on the server is a plus
    - name: install mutt-patched
      apt: pkg=mutt-patched state=present

    - name: configure mutt
      template: >
        src=resources{{ item }}
        dest={{ item }}
        owner=root
        group=root
        mode=644
      with_items:
        - /etc/Muttrc

  handlers:
    - name: run newaliases
      command: newaliases

    - name: restart postfix
      service: name=postfix state=restarted

    - name: restart dovecot
      service: name=dovecot state=restarted
