---
# Install and configure OpenTTD for use as a dedicated server.
# Warning: This installs x11-common and friends (because openttd *requires* sdl)
- hosts: buyvm

  vars_prompt:
    - name: openttd_password
      prompt: OpenTTD server password (blank for public server)
      private: yes
    - name: openttd_rcon_password
      prompt: OpenTTD remote console password (blank to disable)
      private: yes
    - name: openttd_admin_password
      prompt: OpenTTD admin password (blank to disable)
      private: yes

  sudo: yes

  tasks:

    - name: Stop existing OpenTTD server (if it exists)
      service: name=openttd enabled=yes state=started
      ignore_errors: yes

    - name: Ensure /var/games exists
      file: >
        dest=/var/games
        mode=755
        owner=root
        group=root
        state=directory

    - name: Create 'openttd' user
      user: >
        name=openttd
        comment="OpenTTD Server Service"
        system=yes
        home=/var/games/openttd
        createhome=yes

    - name: Create temporary directory
      file: >
        dest=/tmp/ansible-openttd
        mode=700
        owner=openttd
        group=openttd
        state=directory

    - name: Download OpenTTD
      get_url: >
        url=http://binaries.openttd.org/releases/${openttd.version}/openttd-${openttd.version}-linux-debian-${debian_release}-${arch}.deb
        dest=/tmp/ansible-openttd/openttd-${openttd.version}.deb

    - name: Install OpenTTD
      shell: >
        dpkg -i /tmp/ansible-openttd/openttd-${openttd.version}.deb ||
        apt-get -f --no-install-recommends --assume-yes install

    - name: Download OpenGFX
      get_url: >
        url=http://binaries.openttd.org/extra/opengfx/${openttd.opengfx_version}/opengfx-${openttd.opengfx_version}-all.zip
        dest=/tmp/ansible-openttd/opengfx-${openttd.opengfx_version}.zip

    - name: Remove previous OpenGFX installations
      shell: rm -rf /usr/share/games/openttd/baseset/opengfx*

    - name: Install OpenGFX
      command: unzip /tmp/ansible-openttd/opengfx-${openttd.opengfx_version}.zip
                 -d /usr/share/games/openttd/baseset

    - name: Install init.d script
      copy: >
        src=resources/etc/init.d/openttd
        dest=/etc/init.d/openttd
        mode=755
        owner=root
        group=root

    - name: Register init.d script
      command: update-rc.d openttd defaults

    - name: Clean up temporary files
      file: dest=/tmp/ansible-openttd state=absent

    - name: Create OpenTTD gamedata folder
      file: >
        dest=/var/games/openttd/.openttd
        mode=755
        owner=openttd
        group=openttd
        state=directory

    - name: Configure OpenTTD
      template: >
        src=resources/etc/openttd.cfg
        dest=/var/games/openttd/.openttd/openttd.cfg
        mode=600
        owner=openttd
        group=openttd

    - name: Link the OpenTTD config file to the gamedata folder
      file: >
        src=/var/games/openttd/.openttd/openttd.cfg
        dest=/etc/openttd.cfg
        mode=600
        owner=openttd
        group=openttd
        state=link

    # Really, openttd should make this, but it doesn't when run with `-f`
    - name: Create OpenTTD logfile
      copy: >
        src=/dev/null
        dest=/var/games/openttd/.openttd/openttd.log
        mode=644
        owner=openttd
        group=openttd

    - name: Link the OpenTTD logfile to /var/log
      file: >
        src=/var/games/openttd/.openttd/openttd.log
        dest=/var/log/openttd
        mode=644
        owner=openttd
        group=openttd
        state=link

    - name: Start OpenTTD server
      service: name=openttd enabled=yes state=started
