---
- name: run postmap
  command: postmap /etc/postfix/generic

- name: rebuild default sieve
  command: sievec /etc/dovecot/default.sieve

- name: restart postfix
  service: name=postfix state=restarted enabled=yes

- name: restart postgrey
  service: name=postgrey state=restarted enabled=yes

- name: restart dovecot
  service: name=dovecot state=restarted enabled=yes
