---
openttd:
  server_name: Magical Rainbows
  version: 1.3.2 # https://secure.openttd.org/www/en/download-stable
  opengfx_version: 0.4.7
  currency: USD # https://secure.openttd.org/wiki/Currency
  language: ALL
  units: imperial # alternatively, metric
  casual: yes
