---
- name: install dovecot
  apt: pkg={{ item }} state=present
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-sieve

- name: configure dovecot
  action: >
    {{ item.action }}
    src={{ item.file }}{% if item.action == "template" %}.j2{% endif %}
    dest=/etc/{{ item.file }}
    owner=root
    group=root
    mode=644
  with_items:
    - {file: pam.d/dovecot, action: copy}
    - {file: dovecot/conf.d/10-auth.conf, action: template}
    - {file: dovecot/conf.d/10-logging.conf, action: copy}
    - {file: dovecot/conf.d/10-mail.conf, action: copy}
    - {file: dovecot/conf.d/10-master.conf, action: copy}
    - {file: dovecot/conf.d/10-ssl.conf, action: copy}
    - {file: dovecot/conf.d/15-lda.conf, action: template}
    - {file: dovecot/conf.d/90-plugin.conf, action: copy}
    - {file: dovecot/conf.d/auth-system.conf.ext, action: copy}
    - {file: dovecot/conf.d/auth-static.conf.ext, action: template}
    - {file: dovecot/default.sieve, action: copy}
  notify:
    - restart dovecot
    - rebuild default sieve
