- name: install public keys
  gpg_key: >
    id="{{ item.id }}"
    keyserver="{{ item.keyserver }}"
    state=latest
  sudo_user: "{{ primary_user }}"
  with_items: gpg.public
  tags: gpg

- name: install private keys
  gpg_key: >
    file="secrets/{{ item.file }}"
    state=latest
  sudo_user: "{{ primary_user }}"
  with_items: gpg.private
  tags: gpg
